FROM sourcegraph/src-cli:3.38.0@sha256:5d26b9225268c5e49f24ceedf7bae303c9e34640faae3f254f4c8f312d77d4cb AS src-cli

FROM node:17.9.0-alpine3.14@sha256:eb66d0764468ec142edbddeb513b0e591c89e08a0b1d0c9bf23f9284c7611603

ENV NODE_OPTIONS=--max-old-space-size=4096

RUN apk add --no-cache git bash curl ca-certificates python3 make libstdc++ libgcc gcc g++ pkgconfig python2 automake autoconf

COPY --from=src-cli /usr/bin/src /usr/bin

RUN curl -Lo /usr/bin/lsif-typed https://github.com/sourcegraph/lsif-typescript/releases/download/v0.1.13/lsif-typed && chmod +x /usr/bin/lsif-typed

RUN echo 'lsif-typescript "$@" --no-progress-bar && lsif-typed dump.lsif-typed > dump.lsif' > /usr/bin/lsif-typescript-autoindex && chmod +x /usr/bin/lsif-typescript-autoindex

RUN npm install --global n@latest @sourcegraph/lsif-typescript@latest

CMD ["/bin/sh"]
